import { Component } from '@angular/core';
import { AdminSection } from '../../../shared/components/admin-section/admin-section';
import { ServiceCategory } from './components/service-category/service-category';
import { ServiceCategoryGet } from '../../../model/response/service/service-category-get.model';

@Component({
  selector: 'service-manage',
  imports: [AdminSection, ServiceCategory],
  templateUrl: './service-manage.html',
  styleUrl: './service-manage.css',
})
export class ServiceManage {
  mockdata: ServiceCategoryGet[] = [
    {
      id: 1,
      name: 'Hand Nail',
      mainServices: [
        {
          id: 1,
          name: 'Anti-Aging Facial',
          price: 110.0,
          description:
            '60-minute facial designed to reduce fine lines and rejuvenate the skin.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:14:29.260525Z',
          createdBy: 'daokiencuong04@gmail.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 6,
          name: 'Brightening Facial',
          price: 105.0,
          description:
            'Facial treatment to even skin tone and restore radiance.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [
            {
              id: 1,
              name: 'Beard Trim & Styling',
              price: 25.0,
              durationTime: 'PT15M',
              priceType: 'FIXED',
              createdAt: '2025-08-09T14:16:03.839412Z',
              createdBy: 'daokiencuong04@gmail.com',
              updatedAt: null,
              updatedBy: null,
            },
            {
              id: 2,
              name: 'Classic Haircut',
              price: 30.0,
              durationTime: 'PT30M',
              priceType: 'FIXED',
              createdAt: '2025-08-09T14:16:28.925262Z',
              createdBy: 'daokiencuong04@gmail.com',
              updatedAt: null,
              updatedBy: null,
            },
            {
              id: 8,
              name: 'Men’s Hair Styling',
              price: 27.0,
              durationTime: 'PT20M',
              priceType: 'FIXED',
              createdAt: '2025-08-09T14:17:08.664803Z',
              createdBy: 'daokiencuong04@gmail.com',
              updatedAt: null,
              updatedBy: null,
            },
            {
              id: 10,
              name: 'Moustache Grooming',
              price: 15.0,
              durationTime: 'PT10M',
              priceType: 'FIXED',
              createdAt: '2025-08-09T14:17:20.481251Z',
              createdBy: 'daokiencuong04@gmail.com',
              updatedAt: null,
              updatedBy: null,
            },
          ],
          createdAt: '2025-08-09T14:15:25.677222Z',
          createdBy: 'daokiencuong04@gmail.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 7,
          name: 'Luxury Pedicure',
          price: 65.0,
          description: 'Spa pedicure with exfoliation, massage, and polish.',
          durationTime: 'PT45M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:15:36.215305Z',
          createdBy: 'daokiencuong04@gmail.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 10,
          name: 'Collagen Boost Facial',
          price: 120.0,
          description:
            'Facial treatment designed to boost collagen production and firmness.',
          durationTime: 'PT1H5M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:15:50.588743Z',
          createdBy: 'daokiencuong04@gmail.com',
          updatedAt: null,
          updatedBy: null,
        },
      ],
      createdAt: '2025-08-09T14:13:58.213437Z',
      createdBy: 'daokiencuong04@gmail.com',
      updatedAt: null,
      updatedBy: null,
    },
    {
      id: 2,
      name: 'Foot Nail',
      mainServices: [
        {
          id: 2,
          name: 'Deep Tissue Massage',
          price: 85.0,
          description:
            'Relieves tension in deeper muscle layers for full body relaxation.',
          durationTime: 'PT1H30M',
          priceType: 'FIXED',
          subServices: [
            {
              id: 4,
              name: 'Hair Wash & Blow Dry',
              price: 20.0,
              durationTime: 'PT15M',
              priceType: 'FIXED',
              createdAt: '2025-08-09T14:16:41.246403Z',
              createdBy: 'daokiencuong04@gmail.com',
              updatedAt: null,
              updatedBy: null,
            },
          ],
          createdAt: '2025-08-09T14:15:03.773426Z',
          createdBy: 'daokiencuong04@gmail.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 4,
          name: 'Aromatherapy Massage',
          price: 75.0,
          description:
            'Gentle massage with essential oils to relax and uplift mood.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [
            {
              id: 3,
              name: 'Hot Towel Shave',
              price: 28.0,
              durationTime: 'PT20M',
              priceType: 'FIXED',
              createdAt: '2025-08-09T14:16:35.174943Z',
              createdBy: 'daokiencuong04@gmail.com',
              updatedAt: null,
              updatedBy: null,
            },
          ],
          createdAt: '2025-08-09T14:15:15.068449Z',
          createdBy: 'daokiencuong04@gmail.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 5,
          name: 'Hot Stone Therapy',
          price: 90.0,
          description:
            'Heated stones applied to muscles to ease tension and stress.',
          durationTime: 'PT1H20M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:15:20.117316Z',
          createdBy: 'daokiencuong04@gmail.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 8,
          name: 'Swedish Massage',
          price: 70.0,
          description:
            'Classic massage technique for relaxation and circulation.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [
            {
              id: 6,
              name: 'Head Shave',
              price: 22.0,
              durationTime: 'PT15M',
              priceType: 'FIXED',
              createdAt: '2025-08-09T14:16:57.072726Z',
              createdBy: 'daokiencuong04@gmail.com',
              updatedAt: null,
              updatedBy: null,
            },
          ],
          createdAt: '2025-08-09T14:15:41.366621Z',
          createdBy: 'daokiencuong04@gmail.com',
          updatedAt: null,
          updatedBy: null,
        },
      ],
      createdAt: '2025-08-09T14:14:05.715195Z',
      createdBy: 'daokiencuong04@gmail.com',
      updatedAt: null,
      updatedBy: null,
    },
    {
      id: 3,
      name: 'Head Nail',
      mainServices: [
        {
          id: 3,
          name: 'Hydrating Body Wrap',
          price: 95.0,
          description:
            'Full-body treatment to nourish dry skin and improve hydration.',
          durationTime: 'PT1H15M',
          priceType: 'FIXED',
          subServices: [
            {
              id: 7,
              name: 'Beard Coloring',
              price: 40.0,
              durationTime: 'PT25M',
              priceType: 'FIXED',
              createdAt: '2025-08-09T14:17:03.248912Z',
              createdBy: 'daokiencuong04@gmail.com',
              updatedAt: null,
              updatedBy: null,
            },
            {
              id: 9,
              name: 'Beard & Hair Combo',
              price: 50.0,
              durationTime: 'PT45M',
              priceType: 'FIXED',
              createdAt: '2025-08-09T14:17:15.508077Z',
              createdBy: 'daokiencuong04@gmail.com',
              updatedAt: null,
              updatedBy: null,
            },
          ],
          createdAt: '2025-08-09T14:15:09.911072Z',
          createdBy: 'daokiencuong04@gmail.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 9,
          name: 'Detox Mud Wrap',
          price: 100.0,
          description:
            'Body wrap with mineral-rich mud to detoxify and soften skin.',
          durationTime: 'PT1H10M',
          priceType: 'FIXED',
          subServices: [
            {
              id: 5,
              name: 'Fade Haircut',
              price: 35.0,
              durationTime: 'PT35M',
              priceType: 'FIXED',
              createdAt: '2025-08-09T14:16:47.885701Z',
              createdBy: 'daokiencuong04@gmail.com',
              updatedAt: null,
              updatedBy: null,
            },
          ],
          createdAt: '2025-08-09T14:15:46.004026Z',
          createdBy: 'daokiencuong04@gmail.com',
          updatedAt: null,
          updatedBy: null,
        },
      ],
      createdAt: '2025-08-09T14:14:10.386435Z',
      createdBy: 'daokiencuong04@gmail.com',
      updatedAt: null,
      updatedBy: null,
    },
  ];
}
