import { Injectable } from '@angular/core';
import { ServiceCategoryGet } from '../../model/response/service/service-category-get.model';

@Injectable({
  providedIn: 'root'
})
export class BookingService {
    mockdata: ServiceCategoryGet[] = [
    {
      id: 1,
      name: 'Nail Enhancements',
      mainServices: [
        {
          id: 1,
          name: 'Anti-Aging Facial',
          price: 110.0,
          description:
            '60-minute facial designed to reduce fine lines and rejuvenate the skin.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:14:29.260525Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 2,
          name: 'Brightening Facial',
          price: 105.0,
          description:
            'Facial treatment to even skin tone and restore radiance.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:15:25.677222Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 3,
          name: 'Luxury Pedicure',
          price: 65.0,
          description: 'Spa pedicure with exfoliation, massage, and polish.',
          durationTime: 'PT45M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:15:36.215305Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 4,
          name: 'Collagen Boost Facial',
          price: 120.0,
          description:
            'Facial treatment designed to boost collagen production and firmness.',
          durationTime: 'PT1H5M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:15:50.588743Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 5,
          name: 'Nail Art Design',
          price: 40.0,
          description:
            'Creative and artistic nail designs with a variety of colors and styles.',
          durationTime: 'PT1H30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:16:00.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 6,
          name: 'Gel Manicure',
          price: 50.0,
          description:
            'Long-lasting gel manicure for a shiny and durable finish.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:16:10.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 7,
          name: 'French Manicure',
          price: 45.0,
          description:
            'Classic French manicure with white tips and natural pink base.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:16:20.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 8,
          name: 'Paraffin Treatment',
          price: 35.0,
          description:
            'Moisturizing paraffin wax treatment for soft and smooth hands.',
          durationTime: 'PT45M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:16:30.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 9,
          name: 'Hand Massage',
          price: 30.0,
          description:
            'Relaxing hand massage to relieve tension and improve circulation.',
          durationTime: 'PT30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:16:40.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 10,
          name: 'Cuticle Care',
          price: 20.0,
          description: 'Professional cuticle trimming and care.',
          durationTime: 'PT20M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:16:50.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 11,
          name: 'Nail Repair',
          price: 25.0,
          description: 'Repair damaged or broken nails.',
          durationTime: 'PT30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:17:00.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 12,
          name: 'Acrylic Nails',
          price: 55.0,
          description: 'Durable acrylic nails application.',
          durationTime: 'PT1H30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:17:10.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 13,
          name: 'Nail Polish Change',
          price: 15.0,
          description: 'Quick polish change.',
          durationTime: 'PT15M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:17:20.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 14,
          name: 'Nail Buffing',
          price: 10.0,
          description: 'Buffing nails for shine and smoothness.',
          durationTime: 'PT15M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:17:30.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 15,
          name: 'Nail Extension Removal',
          price: 20.0,
          description: 'Safe removal of nail extensions.',
          durationTime: 'PT30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:17:40.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
      ],
      createdAt: '2025-08-09T14:13:58.213437Z',
      createdBy: 'admin@example.com',
      updatedAt: null,
      updatedBy: null,
    },
    {
      id: 2,
      name: 'Natural Nails',
      mainServices: [
        {
          id: 16,
          name: 'Deep Tissue Massage',
          price: 85.0,
          description:
            'Relieves tension in deeper muscle layers for full body relaxation.',
          durationTime: 'PT1H30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:15:03.773426Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 17,
          name: 'Aromatherapy Massage',
          price: 75.0,
          description:
            'Gentle massage with essential oils to relax and uplift mood.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:15:15.068449Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 18,
          name: 'Hot Stone Therapy',
          price: 90.0,
          description:
            'Heated stones applied to muscles to ease tension and stress.',
          durationTime: 'PT1H20M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:15:20.117316Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 19,
          name: 'Swedish Massage',
          price: 70.0,
          description:
            'Classic massage technique for relaxation and circulation.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:15:41.366621Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 20,
          name: 'Foot Reflexology',
          price: 60.0,
          description: 'Therapeutic foot massage focusing on pressure points.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:15:50.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 21,
          name: 'Pedicure',
          price: 50.0,
          description:
            'Classic pedicure treatment including nail care and polish.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:16:00.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 22,
          name: 'Callus Removal',
          price: 40.0,
          description: 'Safe removal of hardened skin and calluses.',
          durationTime: 'PT45M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:16:10.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 23,
          name: 'Foot Soak',
          price: 25.0,
          description: 'Relaxing foot soak with essential oils.',
          durationTime: 'PT30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:16:20.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 24,
          name: 'Toenail Care',
          price: 30.0,
          description: 'Professional toenail trimming and care.',
          durationTime: 'PT30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:16:30.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 25,
          name: 'Foot Massage',
          price: 35.0,
          description: 'Relaxing foot massage to improve circulation.',
          durationTime: 'PT30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:16:40.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 26,
          name: 'Exfoliation',
          price: 20.0,
          description: 'Foot exfoliation to remove dead skin.',
          durationTime: 'PT20M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:16:50.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 27,
          name: 'Foot Scrub',
          price: 22.0,
          description: 'Gentle foot scrub for smooth skin.',
          durationTime: 'PT20M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:17:00.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 28,
          name: 'Foot Wrap',
          price: 28.0,
          description: 'Hydrating foot wrap treatment.',
          durationTime: 'PT30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:17:10.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 29,
          name: 'Reflexology',
          price: 50.0,
          description: 'Pressure point therapy on feet.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:17:20.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 30,
          name: 'Foot Detox',
          price: 55.0,
          description: 'Detoxifying foot treatment.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:17:30.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
      ],
      createdAt: '2025-08-09T14:14:05.715195Z',
      createdBy: 'admin@example.com',
      updatedAt: null,
      updatedBy: null,
    },
    {
      id: 3,
      name: 'Combo',
      mainServices: [
        {
          id: 31,
          name: 'Hydrating Body Wrap',
          price: 95.0,
          description:
            'Full-body treatment to nourish dry skin and improve hydration.',
          durationTime: 'PT1H15M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:15:09.911072Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 32,
          name: 'Detox Mud Wrap',
          price: 100.0,
          description:
            'Body wrap with mineral-rich mud to detoxify and soften skin.',
          durationTime: 'PT1H10M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:15:46.004026Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 33,
          name: 'Beard Coloring',
          price: 40.0,
          description: 'Coloring treatment for beard.',
          durationTime: 'PT25M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:17:03.248912Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 34,
          name: 'Beard & Hair Combo',
          price: 50.0,
          description: 'Combined beard and hair styling.',
          durationTime: 'PT45M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:17:15.508077Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 35,
          name: 'Haircut & Style',
          price: 60.0,
          description: 'Professional haircut and styling.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:17:40.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 36,
          name: 'Facial Treatment',
          price: 80.0,
          description: 'Refreshing facial treatment.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:18:00.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 37,
          name: 'Scalp Massage',
          price: 30.0,
          description: 'Relaxing scalp massage.',
          durationTime: 'PT30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:18:20.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 38,
          name: 'Hair Coloring',
          price: 70.0,
          description: 'Professional hair coloring service.',
          durationTime: 'PT1H30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:18:40.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 39,
          name: 'Beard Trim',
          price: 25.0,
          description: 'Beard trimming and styling.',
          durationTime: 'PT20M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:19:00.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 40,
          name: 'Shaving',
          price: 20.0,
          description: 'Classic shaving service.',
          durationTime: 'PT15M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:19:20.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 41,
          name: 'Hair Treatment',
          price: 65.0,
          description: 'Nourishing hair treatment.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:19:40.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 42,
          name: 'Head Shave',
          price: 22.0,
          description: 'Professional head shave.',
          durationTime: 'PT15M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:20:00.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 43,
          name: 'Hair Styling',
          price: 50.0,
          description: 'Styling hair for events and daily look.',
          durationTime: 'PT45M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:20:20.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 44,
          name: 'Detox Treatment',
          price: 55.0,
          description: 'Detoxifying scalp and hair treatment.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:20:40.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 45,
          name: 'Hot Towel Shave',
          price: 28.0,
          description: 'Comforting hot towel shave.',
          durationTime: 'PT20M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-09T14:21:00.000000Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
      ],
      createdAt: '2025-08-09T14:14:10.386435Z',
      createdBy: 'admin@example.com',
      updatedAt: null,
      updatedBy: null,
    },
    {
      id: 4,
      name: 'Waxing',
      mainServices: [
        {
          id: 46,
          name: 'Swedish Massage',
          price: 80.0,
          description: 'Relaxing full body massage.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-10T10:00:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 47,
          name: 'Aromatherapy',
          price: 90.0,
          description: 'Aromatherapy massage with essential oils.',
          durationTime: 'PT1H30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-10T10:10:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 48,
          name: 'Deep Tissue Massage',
          price: 100.0,
          description: 'Deep muscle tissue massage.',
          durationTime: 'PT1H45M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-10T10:20:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 49,
          name: 'Hot Stone Therapy',
          price: 110.0,
          description: 'Therapeutic hot stone treatment.',
          durationTime: 'PT2H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-10T10:30:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 50,
          name: 'Body Scrub',
          price: 70.0,
          description: 'Exfoliating full body scrub.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-10T10:40:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 51,
          name: 'Body Wrap',
          price: 95.0,
          description: 'Detoxifying body wrap.',
          durationTime: 'PT1H30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-10T10:50:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 52,
          name: 'Cellulite Treatment',
          price: 85.0,
          description: 'Treatment to reduce cellulite.',
          durationTime: 'PT1H15M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-10T11:00:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 53,
          name: 'Lymphatic Drainage',
          price: 75.0,
          description: 'Massage to stimulate lymph flow.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-10T11:10:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 54,
          name: 'Back Massage',
          price: 60.0,
          description: 'Focused back massage.',
          durationTime: 'PT45M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-10T11:20:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 55,
          name: 'Foot Massage',
          price: 50.0,
          description: 'Relaxing foot massage.',
          durationTime: 'PT30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-10T11:30:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 56,
          name: 'Hand Massage',
          price: 45.0,
          description: 'Soothing hand massage.',
          durationTime: 'PT30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-10T11:40:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 57,
          name: 'Aromatherapy Wrap',
          price: 70.0,
          description: 'Aromatherapy body wrap.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-10T11:50:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 58,
          name: 'Relaxation Massage',
          price: 65.0,
          description: 'Full body relaxation massage.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-10T12:00:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 59,
          name: 'Sports Massage',
          price: 85.0,
          description: 'Massage for athletes and muscle recovery.',
          durationTime: 'PT1H30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-10T12:10:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
      ],
      createdAt: '2025-08-10T09:00:00Z',
      createdBy: 'admin@example.com',
      updatedAt: null,
      updatedBy: null,
    },
    {
      id: 5,
      name: 'Add Ons',
      mainServices: [
        {
          id: 60,
          name: 'Haircut',
          price: 40.0,
          description: 'Professional haircut service.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T09:00:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 61,
          name: 'Hair Coloring',
          price: 70.0,
          description: 'Full hair coloring service.',
          durationTime: 'PT1H30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T09:10:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 62,
          name: 'Blow Dry',
          price: 30.0,
          description: 'Professional blow drying.',
          durationTime: 'PT45M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T09:20:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 63,
          name: 'Perm',
          price: 80.0,
          description: 'Perming hair for curls or waves.',
          durationTime: 'PT2H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T09:30:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 64,
          name: 'Hair Treatment',
          price: 60.0,
          description: 'Nourishing hair treatment.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T09:40:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 65,
          name: 'Scalp Massage',
          price: 25.0,
          description: 'Relaxing scalp massage.',
          durationTime: 'PT30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T09:50:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 66,
          name: 'Hair Styling',
          price: 45.0,
          description: 'Styling hair for special occasions.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T10:00:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 67,
          name: 'Hair Extensions',
          price: 100.0,
          description: 'Adding hair extensions for volume and length.',
          durationTime: 'PT2H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T10:10:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 68,
          name: 'Highlights',
          price: 75.0,
          description: 'Adding highlights to hair.',
          durationTime: 'PT1H30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T10:20:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 69,
          name: 'Hair Relaxing',
          price: 85.0,
          description: 'Relaxing curly or frizzy hair.',
          durationTime: 'PT1H45M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T10:30:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 70,
          name: 'Hair Color Correction',
          price: 90.0,
          description: 'Correcting hair color mistakes.',
          durationTime: 'PT2H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T10:40:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 71,
          name: 'Hair Treatment Mask',
          price: 55.0,
          description: 'Deep conditioning hair mask.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T10:50:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 72,
          name: 'Hair Scalp Treatment',
          price: 50.0,
          description: 'Treatment for scalp health.',
          durationTime: 'PT45M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T11:00:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 73,
          name: 'Blowout Styling',
          price: 40.0,
          description: 'Voluminous blowout styling.',
          durationTime: 'PT45M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T11:10:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 74,
          name: 'Updo Styling',
          price: 70.0,
          description: 'Elegant updo hairstyle.',
          durationTime: 'PT1H30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T11:20:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
      ],
      createdAt: '2025-08-11T08:00:00Z',
      createdBy: 'admin@example.com',
      updatedAt: null,
      updatedBy: null,
    },
    {
      id: 5,
      name: 'Hair Care',
      mainServices: [
        {
          id: 60,
          name: 'Haircut',
          price: 40.0,
          description: 'Professional haircut service.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T09:00:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 61,
          name: 'Hair Coloring',
          price: 70.0,
          description: 'Full hair coloring service.',
          durationTime: 'PT1H30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T09:10:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 62,
          name: 'Blow Dry',
          price: 30.0,
          description: 'Professional blow drying.',
          durationTime: 'PT45M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T09:20:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 63,
          name: 'Perm',
          price: 80.0,
          description: 'Perming hair for curls or waves.',
          durationTime: 'PT2H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T09:30:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 64,
          name: 'Hair Treatment',
          price: 60.0,
          description: 'Nourishing hair treatment.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T09:40:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 65,
          name: 'Scalp Massage',
          price: 25.0,
          description: 'Relaxing scalp massage.',
          durationTime: 'PT30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T09:50:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 66,
          name: 'Hair Styling',
          price: 45.0,
          description: 'Styling hair for special occasions.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T10:00:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 67,
          name: 'Hair Extensions',
          price: 100.0,
          description: 'Adding hair extensions for volume and length.',
          durationTime: 'PT2H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T10:10:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 68,
          name: 'Highlights',
          price: 75.0,
          description: 'Adding highlights to hair.',
          durationTime: 'PT1H30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T10:20:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 69,
          name: 'Hair Relaxing',
          price: 85.0,
          description: 'Relaxing curly or frizzy hair.',
          durationTime: 'PT1H45M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T10:30:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 70,
          name: 'Hair Color Correction',
          price: 90.0,
          description: 'Correcting hair color mistakes.',
          durationTime: 'PT2H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T10:40:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 71,
          name: 'Hair Treatment Mask',
          price: 55.0,
          description: 'Deep conditioning hair mask.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T10:50:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 72,
          name: 'Hair Scalp Treatment',
          price: 50.0,
          description: 'Treatment for scalp health.',
          durationTime: 'PT45M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T11:00:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 73,
          name: 'Blowout Styling',
          price: 40.0,
          description: 'Voluminous blowout styling.',
          durationTime: 'PT45M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T11:10:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 74,
          name: 'Updo Styling',
          price: 70.0,
          description: 'Elegant updo hairstyle.',
          durationTime: 'PT1H30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T11:20:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
      ],
      createdAt: '2025-08-11T08:00:00Z',
      createdBy: 'admin@example.com',
      updatedAt: null,
      updatedBy: null,
    },{
      id: 5,
      name: 'Hair Care',
      mainServices: [
        {
          id: 60,
          name: 'Haircut',
          price: 40.0,
          description: 'Professional haircut service.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T09:00:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 61,
          name: 'Hair Coloring',
          price: 70.0,
          description: 'Full hair coloring service.',
          durationTime: 'PT1H30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T09:10:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 62,
          name: 'Blow Dry',
          price: 30.0,
          description: 'Professional blow drying.',
          durationTime: 'PT45M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T09:20:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 63,
          name: 'Perm',
          price: 80.0,
          description: 'Perming hair for curls or waves.',
          durationTime: 'PT2H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T09:30:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 64,
          name: 'Hair Treatment',
          price: 60.0,
          description: 'Nourishing hair treatment.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T09:40:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 65,
          name: 'Scalp Massage',
          price: 25.0,
          description: 'Relaxing scalp massage.',
          durationTime: 'PT30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T09:50:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 66,
          name: 'Hair Styling',
          price: 45.0,
          description: 'Styling hair for special occasions.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T10:00:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 67,
          name: 'Hair Extensions',
          price: 100.0,
          description: 'Adding hair extensions for volume and length.',
          durationTime: 'PT2H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T10:10:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 68,
          name: 'Highlights',
          price: 75.0,
          description: 'Adding highlights to hair.',
          durationTime: 'PT1H30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T10:20:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 69,
          name: 'Hair Relaxing',
          price: 85.0,
          description: 'Relaxing curly or frizzy hair.',
          durationTime: 'PT1H45M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T10:30:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 70,
          name: 'Hair Color Correction',
          price: 90.0,
          description: 'Correcting hair color mistakes.',
          durationTime: 'PT2H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T10:40:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 71,
          name: 'Hair Treatment Mask',
          price: 55.0,
          description: 'Deep conditioning hair mask.',
          durationTime: 'PT1H',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T10:50:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 72,
          name: 'Hair Scalp Treatment',
          price: 50.0,
          description: 'Treatment for scalp health.',
          durationTime: 'PT45M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T11:00:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 73,
          name: 'Blowout Styling',
          price: 40.0,
          description: 'Voluminous blowout styling.',
          durationTime: 'PT45M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T11:10:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
        {
          id: 74,
          name: 'Updo Styling',
          price: 70.0,
          description: 'Elegant updo hairstyle.',
          durationTime: 'PT1H30M',
          priceType: 'FIXED',
          subServices: [],
          createdAt: '2025-08-11T11:20:00Z',
          createdBy: 'admin@example.com',
          updatedAt: null,
          updatedBy: null,
        },
      ],
      createdAt: '2025-08-11T08:00:00Z',
      createdBy: 'admin@example.com',
      updatedAt: null,
      updatedBy: null,
    },
  ];

  getAllService(): ServiceCategoryGet[]{
    return this.mockdata;
  }
}
